### ISSUE TITLE
Cannot store configuration on Windows

### ISSUE THREAD

**Issue by ghost** [dnlzrgz/housaku#2]
This entry suggests default storage locations for e.g. $XDG_CONFIG_HOME: https://stackoverflow.com/questions/43853548/xdg-basedir-directories-for-windows
However, there is also a library `appdirs` that has cross-platform helpers for that.

**Comment by dnlzrgz** [comment]
Since I'm using `click` I decided to use the `get_app_dir` utility function (https://click.palletsprojects.com/en/8.1.x/api/#click.get_app_dir), which is supposed to handle the setup correctly on Windows.

**Comment by ArneBachmann** [comment]
Thanks, that works better!
